### ISSUE TITLE
Issue: report.html renders only #<HowIs:0x007fae56966700>

### ISSUE THREAD

**Issue by olleolleolle** [how-is/how_is#149]
The `send("to_#{format}")` which was removed from the last commit made the `how_is` report.html look like this:

```
 ~ cat report.html
#<HowIs:0x007fae56966700>%
```

Perhaps there needs to be a `#to_s` on that class, or something?

Using the previous implementation (here with `public_send`) works:

```ruby
def save_files(reports)
  reports.each do |file, report|
    format = file.split('.').last

    File.open(file, 'w') do |f|
      f.write report.public_send("to_#{format}")
    end
  end
end
```

**Comment by duckinator** [comment]
Oh, shit, right. `HowIs.from_config` automatically runs an equivalent to `.to_#{report_format}` because it has the information to do so. However, the other execution path has to infer this information and run it itself. I was trying to combine functions at the wrong abstraction level.

It needs to be something like

```ruby
def save_report(file, report)
  File.open(file, 'w') do |f|
    f.write report
  end
end

def infer_format(file)
  Pathname(file).extname.delete('.')
end

# Maybe a better name?
def report_to_inferred_format(file, report)
  report_format = infer_format(file)

  report.public_send("to_#{report_format}")
end
```

then have the `options[:config]` part do something like

```ruby
reports.each { |file, report| save_report(file, report) }
```

and have the other part of that if statement do something like

```ruby
save_report(options[:report], report_to_inferred_format(file, report)
```
