### ISSUE TITLE
Track new contributors

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#172]
Track new contributors for the report period (for Ruby Together monthly update script).

**Comment by duckinator** [comment]
Possible approach:

1. get a list of all commits during the given period (from /compare)
2. get a list of all contributors for those commits
3. scrape `https://github.com/rubygems/rubygems/commits?author=#{github_handle}` and see if they made any commits that aren't in the list from # 1

**Comment by olleolleolle** [comment]
Getting New Contributors is about listing who "has no commits yet".

Ellen Marie came up with this simple API usage:

1. `how_is` is date-based, so we need `/repos/:owner/:repo/commits?since=<start date for the report>` to get a list of authors 
2. and for each committer: `/repos/:owner/:repo/commits?until=<start date for the report>&author=<committer>`, and if that's empty **they're a new contributor**

**Comment by duckinator** [comment]
As a note, depending on commits since there _may_ be multiple pages for the first API call. iirc the github_api gem can handle this for you automagically, but you'll need to explicitly tell it to.
