### ISSUE TITLE
Travis CI: Configure HOWIS_BASIC_AUTH et al

### ISSUE THREAD

**Issue by olleolleolle** [how-is/how_is#240]
HOWIS_BASIC_AUTH is missing, the tests complain.

**Comment by duckinator** [comment]
As discovered in #236, at some point Travis CI added [new security restrictions for pull requests](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).

While these security restrictions make sense, they do make it significantly more difficult to test pull requests, because only pull requests made from the same repo have access to encrypted environment variables.

In #237, I made it so that the exceptions are thrown when the environment variables are used, not at the start, so it at least shows proper results for _some_ tests.

The two environment variables used are `HOWIS_BASIC_AUTH` and `HOWIS_GITHUB_TOKEN`. Note that issue #241 (Refactor Sources::Github.basic_auth) may affect the environment variables.

**Comment by duckinator** [comment]
Short term, that approach (or something very similar) seems like the best option.

Long term, I'm not sure how I want to approach. Doing that means there are two different sets of tests ran depending on the environment, despite all used environment variables being _required_ for the program to function correctly. And that makes this approach feel like a kludge.
